### ISSUE TITLE
Jenkins Auto-Build

### ISSUE THREAD

**Issue by Tbsc** [kfaryarok/kfaryarok-android#18]
Right now, Jenkins builds are configured to run every 24 hours, and to setup building on every push, you need to add Jenkins as a service in the repo's settings.

1. Go to "Settings",
2. Go to "Integrations & services"
3. Click on "Add service"
4. Select "Jenkins (GitHub plugin)" (use the searchbox)
5. In the "Jenkins hook url" textbox, enter exactly this:
    `http://tbscdev.xyz:8080/github-webhook`
6. Make sure "Active" is turned on
7. Click "Add service"

After that, builds will automatically start when pushed, with a maximum of 2 builds per hour.

**Comment by rootatkali** [comment]
Done, adding a simple commit to test

**Comment by Tbsc** [comment]
Trying something else, do the same thing but instead of selecting "Jenkins (GitHub plugin)", select "Jenkins (Git plugin)", and in the "Jenkins url" textbox put `http://tbscdev.xyz:8080`

**Comment by rootatkali** [comment]
Done w/ the Git plugin

**Comment by rootatkali** [comment]
Checked our Jenkins server, working
