### ISSUE TITLE
[BUG] Classes showing in updates is bugged

### ISSUE THREAD

**Issue by rootatkali** [kfaryarok/kfaryarok-android#22]
## Specs
- Developer mode: active
- Class set to: ז4
- Build version: \#38 (April 18, 2017)
- Update server: https://kfaryarok.github.io/update.json

## Picture:
![whatsapp image 2017-04-18 at 19 57 42](https://cloud.githubusercontent.com/assets/26087126/25143158/1373f0cc-2472-11e7-9897-e407ad16be98.jpeg)

## Description:
Classes view is bugged.

**Comment by Tbsc** [comment]
Looking into it
