### ISSUE TITLE
Suggestions for the future

### ISSUE THREAD

**Issue by Tbsc** [kfaryarok/kfaryarok-android#27]
1. ~~If the update text is long, "fold" the update card and allow it to be expanded and closed by clicking on it. Done, I'll pull request it sometime in the future~~ It's in master

**Comment by rootatkali** [comment]
Maybe version numbers on the "About" activity?

**Comment by Tbsc** [comment]
There aren't really any version numbers yet, but I do need to think what to put there.

**Comment by rootatkali** [comment]
Because of the GPL-3.0, we have to put a GPL disclaimer.

**Comment by Tbsc** [comment]
I'll do that later today, Android Studio let's you do that easily to all files

**Comment by Tbsc** [comment]
Done
Edit: syntax of the disclaimer can be easily changed, so tell me if you think it should be different
