### ISSUE TITLE
Repo admin permissions

### ISSUE THREAD

**Issue by Tbsc** [kfaryarok/kfaryarok-android#29]
Seeing as I'm the only one who actually works on this app, I think I should have admin permission for this repo. It would make development much faster, as I wouldn't have to rely on @rootatkali to merge my pull requests. I'm still going to start new work on separate branches, but having the ability to merge to master on my own would be nice.

**Comment by rootatkali** [comment]
Did it

**Comment by Tbsc** [comment]
Thanks
